#!/bin/bash

set -e
cd "$(dirname "$0")/.."

if [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

echo "==> Creating directories"
mkdir -p ~/.vim/{plugged,backups,swap,tmp}

echo "==> Creating symlinks…"
rcup -v -d home
